
version: "3.1"
services:

    mailhog:
      image: mailhog/mailhog:latest
      container_name: racealert-mailhog
      ports:
        - "8889:8025"

    mariadb:
      image: mariadb:10.1
      container_name: racealert-mariadb
      working_dir: /RaceAlert
      volumes:
        - ./:/RaceAlert
      environment:
        - MYSQL_ROOT_PASSWORD=ARootPassword
        - MYSQL_DATABASE=racealert
        - MYSQL_USER=applicationUser
        - MYSQL_PASSWORD=applicationUsersPassword
      ports:
        - "8891:3306"

    webserver:
      image: nginx:alpine
      container_name: racealert-webserver
      working_dir: /RaceAlert
      volumes:
          - ./RaceAlert:/RaceAlert
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8888:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: racealert-php-fpm
      working_dir: /RaceAlert
      volumes:
        - ./RaceAlert:/RaceAlert
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

