<?php

namespace RaceAlertBundle\Repository;

/**
 * TrackConfigurationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrackConfigurationRepository extends \Doctrine\ORM\EntityRepository
{
}
